### ISSUE TITLE
Add screenshots to the readme

### ISSUE THREAD

**Issue by aloisdg** [Suhmedoh/themer.edit#1]
You have plenty of them and the result is gorgeous!
http://imgur.com/a/ODWHY

**Comment by Suhmedoh** [comment]
Done! Knew I was missing something :P
README.md is going to be considered a work in progress until I do some more work on the templates and get rid of whatever doesn't work/ extraneous code and I get a couple people to test it

**Comment by aloisdg** [comment]
Nice. Good continuation!
